/*
 * Generated by JasperReports - 12/15/22 2:43 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class report32name_1671090209934_450507 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_MaHopDong = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_MaVe = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_MaTour = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillField field_Ve_MaVe = null;
    private JRFillField field_Ve_SoLuongVeNguoiLon = null;
    private JRFillField field_Tour_TenTour = null;
    private JRFillField field_ChucVu_TenChucVu = null;
    private JRFillField field_NhanVien_SDT = null;
    private JRFillField field_HopDong_SoLuongKhach = null;
    private JRFillField field_Ve_SoLuongVeTreEm = null;
    private JRFillField field_KhachHang_Email = null;
    private JRFillField field_Tour_MaTour = null;
    private JRFillField field_Ve_TongTien = null;
    private JRFillField field_HopDong_MaHopDong = null;
    private JRFillField field_NhanVien_TenNhanVien = null;
    private JRFillField field_HopDong_NgayLapHopDong = null;
    private JRFillField field_NhanVien_DiaChi = null;
    private JRFillField field_KhachHang_SDT = null;
    private JRFillField field_KhachHang_DiaChi = null;
    private JRFillField field_Ve_MaTour = null;
    private JRFillField field_KhachHang_GioiTinh = null;
    private JRFillField field_Ve_NgayBan = null;
    private JRFillField field_KhachHang_TenKhachHang = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_MASTER_CURRENT_PAGE = null;
    private JRFillVariable variable_MASTER_TOTAL_PAGES = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_MaHopDong = (JRFillParameter)pm.get("MaHopDong");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_MaVe = (JRFillParameter)pm.get("MaVe");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_MaTour = (JRFillParameter)pm.get("MaTour");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_Ve_MaVe = (JRFillField)fm.get("Ve_MaVe");
        field_Ve_SoLuongVeNguoiLon = (JRFillField)fm.get("Ve_SoLuongVeNguoiLon");
        field_Tour_TenTour = (JRFillField)fm.get("Tour_TenTour");
        field_ChucVu_TenChucVu = (JRFillField)fm.get("ChucVu_TenChucVu");
        field_NhanVien_SDT = (JRFillField)fm.get("NhanVien_SDT");
        field_HopDong_SoLuongKhach = (JRFillField)fm.get("HopDong_SoLuongKhach");
        field_Ve_SoLuongVeTreEm = (JRFillField)fm.get("Ve_SoLuongVeTreEm");
        field_KhachHang_Email = (JRFillField)fm.get("KhachHang_Email");
        field_Tour_MaTour = (JRFillField)fm.get("Tour_MaTour");
        field_Ve_TongTien = (JRFillField)fm.get("Ve_TongTien");
        field_HopDong_MaHopDong = (JRFillField)fm.get("HopDong_MaHopDong");
        field_NhanVien_TenNhanVien = (JRFillField)fm.get("NhanVien_TenNhanVien");
        field_HopDong_NgayLapHopDong = (JRFillField)fm.get("HopDong_NgayLapHopDong");
        field_NhanVien_DiaChi = (JRFillField)fm.get("NhanVien_DiaChi");
        field_KhachHang_SDT = (JRFillField)fm.get("KhachHang_SDT");
        field_KhachHang_DiaChi = (JRFillField)fm.get("KhachHang_DiaChi");
        field_Ve_MaTour = (JRFillField)fm.get("Ve_MaTour");
        field_KhachHang_GioiTinh = (JRFillField)fm.get("KhachHang_GioiTinh");
        field_Ve_NgayBan = (JRFillField)fm.get("Ve_NgayBan");
        field_KhachHang_TenKhachHang = (JRFillField)fm.get("KhachHang_TenKhachHang");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_MASTER_CURRENT_PAGE = (JRFillVariable)vm.get("MASTER_CURRENT_PAGE");
        variable_MASTER_TOTAL_PAGES = (JRFillVariable)vm.get("MASTER_TOTAL_PAGES");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = null; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "C:\\Users\\Thuy\\Desktop\\DuAn1\\BackUp_DuAn1\\GreenHouse\\src\\com\\GreenHouse\\Export\\"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = null; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)field_HopDong_MaHopDong.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)field_NhanVien_SDT.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)field_ChucVu_TenChucVu.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)field_NhanVien_TenNhanVien.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.sql.Date)field_HopDong_NgayLapHopDong.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_KhachHang_TenKhachHang.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_KhachHang_DiaChi.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_KhachHang_Email.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_KhachHang_SDT.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_NhanVien_DiaChi.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)field_Tour_TenTour.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubTenKS.jasper"; //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubLT.jasper"; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "Sub_ThoiGianDiChuyen.jasper"; //$JR_EXPR_ID=38$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = null; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "C:\\Users\\Thuy\\Desktop\\DuAn1\\BackUp_DuAn1\\GreenHouse\\src\\com\\GreenHouse\\Export\\"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = null; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)field_HopDong_MaHopDong.getOldValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)field_NhanVien_SDT.getOldValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)field_ChucVu_TenChucVu.getOldValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)field_NhanVien_TenNhanVien.getOldValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.sql.Date)field_HopDong_NgayLapHopDong.getOldValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_KhachHang_TenKhachHang.getOldValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_KhachHang_DiaChi.getOldValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_KhachHang_Email.getOldValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_KhachHang_SDT.getOldValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_NhanVien_DiaChi.getOldValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)field_Tour_TenTour.getOldValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubTenKS.jasper"; //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubLT.jasper"; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "Sub_ThoiGianDiChuyen.jasper"; //$JR_EXPR_ID=38$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = null; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "C:\\Users\\Thuy\\Desktop\\DuAn1\\BackUp_DuAn1\\GreenHouse\\src\\com\\GreenHouse\\Export\\"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = null; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)field_HopDong_MaHopDong.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)field_NhanVien_SDT.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)field_ChucVu_TenChucVu.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)field_NhanVien_TenNhanVien.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.sql.Date)field_HopDong_NgayLapHopDong.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_KhachHang_TenKhachHang.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_KhachHang_DiaChi.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)field_KhachHang_Email.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)field_KhachHang_SDT.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)field_NhanVien_DiaChi.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)field_Tour_TenTour.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubTenKS.jasper"; //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "XuatHopDong_SubLT.jasper"; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_MaHopDong.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_MaVe.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_MaTour.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "Sub_ThoiGianDiChuyen.jasper"; //$JR_EXPR_ID=38$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
